services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crate_raters
      POSTGRES_PASSWORD: crate_raters
      POSTGRES_DB: crate_raters
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: crateraters
      MINIO_ROOT_PASSWORD: crateraters
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  pg-data:
  minio-data:
