services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crate_raters
      POSTGRES_PASSWORD: crate_raters
      POSTGRES_DB: crate_raters
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
